#!/bin/bash

# Check if DOTFILES and STOW_FOLDERS are set
if [ -z "$DOTFILES" ]; then
    echo "DOTFILES environment variable is not set!"
    exit 1
fi

if [ -z "$STOW_FOLDERS" ]; then
    echo "STOW_FOLDERS environment variable is not set!"
    exit 1
fi

# Navigate to the dotfiles directory
pushd "$DOTFILES" || exit 1

# Loop through each folder and apply stow
for folder in $(echo "$STOW_FOLDERS" | sed "s/,/ /g")
do
    echo "Processing folder: $folder"

    # Unstow and then stow the folder
    stow -D "$folder" || { echo "Failed to unstow $folder"; continue; }
    stow "$folder" || { echo "Failed to stow $folder"; continue; }
done

# Return to the original directory
popd || exit 1

