# NOTEBOOK SETTINGS
[notebook]
dir = "~/notebook"

# NOTE SETTINGS
[note]

# Language used when writing notes.
# This is used to generate slugs or with date formats.
language = "en"

# The default title used for new note, if no `--title` flag is provided.
default-title = "Untitled"

# Template used to generate a note's filename, without extension.
filename = "{{format-date now 'timestamp'}}"

# The file extension used for the notes.
extension = "md"

# Template used to generate a note's content.
# If not an absolute path, it is relative to .zk/templates/
template = "default.md"

# Configure random ID generation.
id-charset = "alphanum"
id-length = 4
id-case = "lower"

[extra]
author = "Max Ronner"

[group.journal]
paths = ["journal/weekly", "journal/daily"]

[group.journal.note]
filename = "{{format-date now}}"

[format.markdown]
hashtags = true
colon-tags = true

[tool]
editor = "nvim"
shell = "/bin/bash"
pager = "less -FIRX"
fzf-preview = "bat -p --color always {-1}"

[filter]
recents = "--sort created- --created-after 'last two weeks'"

[alias]
edlast = "zk edit --limit 1 --sort modified- $@"
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"
lucky = "zk list --quiet --format full --sort random --limit 1"
ls = "zk edit --interactive"
t = "zk edit --interactive --tag $argv"
config = 'nvim "$XDG_CONFIG_HOME/zk/config.toml"'
daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/journal"'
ne = 'zk new --no-input "$ZK_NOTEBOOK_DIR/ideas" --title $argv'
journal = "zk edit --sort created- $ZK_NOTEBOOK_DIR/journal --interactive"
ideas = "zk edit --sort created- $ZK_NOTEBOOK_DIR/ideas --interactive"

[lsp]

[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"
