#:schema https://raw.githubusercontent.com/joshmedeski/sesh/refs/heads/main/sesh.schema.json
blacklist = ["scratch"]
cache = false

[default_session]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "mail"
path = "~/"
startup_command = "neomutt"

[[session]]
name = "downloads"
path = "~/Downloads"
startup_command = "l"

[[session]]
name = "notebook"
path = "~/personal/notebook"
windows = [ "agent" ]

[[session]]
name = "nvim"
path = "~/.config/nvim"
startup_command = "v"

[[session]]
name = "dotfiles"
path = "~/.dotfiles"
startup_command = "v"

[[session]]
name = "work"
path = "~/personal/**"
startup_command = "v"

[[wildcard]]
pattern = "~/code/**"
startup_command = "v"
windows = [ "agent" ]

[[window]]
name = "git"
startup_script = "command -v lazygit >/dev/null 2>&1 && lazygit || git status"

[[window]]
name = "opencode"
startup_script = "opencode-serve"
