format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

palette = "rose-pine-moon"

[palettes.rose-pine-moon]
overlay = '#393552'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_status]
style = "fg:love"
format = '[$all_status$ahead_behind]($style)'
up_to_date = '[✓](fg:foam)'
untracked = '[?\($count\)](fg:gold)'
stashed = '[≡](fg:rose)'
modified = '[!\($count\)](fg:gold)'
renamed = '[»\($count\)](fg:iris)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](fg:gold)'
ahead = '[⇡\(${count}\)](fg:foam)'
diverged = '⇕[\[](fg:iris)[⇡\(${ahead_count}\)](fg:foam)[⇣\(${behind_count}\)](fg:rose)[\]](fg:iris)'
behind = '[⇣\(${count}\)](fg:rose)'

[git_branch]
format = "on [$branch(:$remote_branch)]($style) "
truncation_symbol = "⋯"
truncation_length = 11
only_attached = true

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = false

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
