[notebook]
dir = "~/personal/notebook"

[note]
# This is used to generate slugs or with date formats.
language = "en"
default-title = "Untitled"
filename = "{{id}}"
extension = "md"
template = "default.md"

# Configure random ID generation.
id-charset = "hex"
id-length = 8
id-case = "lower"

[extra]
author = "Max Ronner"

[group.weekly]
paths = ["journal/weekly"]

[group.weekly.note]
filename = "{{format-date now}}"

[group.daily]
paths = ["journal/daily"]

[group.daily.note]
filename = "{{format-date now}}"
template = "daily.md"

[format.markdown]
hashtags = true
colon-tags = true

[tool]
editor = "nvim"
shell = "/bin/bash"
pager = "less -FIRX"
fzf-preview = "bat -p --color always {-1}"

[filter]
recents = "--sort created- --created-after 'last two weeks'"

[alias]
edlast = "zk edit --limit 1 --sort modified- $@"
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"
lucky = "zk list --quiet --format full --sort random --limit 1"
ls = "zk edit --interactive"
t = "zk edit --interactive --tag $@"
daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/journal/daily"'
ne = 'zk new --no-input "$ZK_NOTEBOOK_DIR/ideas" --title $@'
journal = "zk edit --sort created- $ZK_NOTEBOOK_DIR/journal --interactive"
ideas = "zk edit --sort created- $ZK_NOTEBOOK_DIR/ideas --interactive"

[lsp]

[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"
