[Unit]
Requisite=
Requires=sway-session.target
PartOf=sway-session.target
After=sway-session.target

[Service]
NoNewPrivileges=yes
ProtectSystem=full
PrivateTmp=yes

[Install]
WantedBy=sway-session.target
